//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuddi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_MgrLog
    {
        public int ID { get; set; }
        public int MgrID { get; set; }
        public string IP { get; set; }
        public int Action { get; set; }
        public string Remark { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
