//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuddi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD_Term
    {
        public int ID { get; set; }
        public string TermNo { get; set; }
        public int ProductID { get; set; }
        public int DictionaryID { get; set; }
        public int Current { get; set; }
        public int Rest { get; set; }
        public int Total { get; set; }
        public int DefaultValue { get; set; }
        public bool AutoStart { get; set; }
        public bool DelFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
