//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuddi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class od_v_product_dictionary
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int DictionaryID { get; set; }
        public string DictionaryName { get; set; }
        public int Type { get; set; }
        public int Key { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
    }
}
