//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuddi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneDreamEntities : DbContext
    {
        public OneDreamEntities()
            : base("name=OneDreamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OD_Manager> OD_Manager { get; set; }
        public virtual DbSet<OD_MgrLog> OD_MgrLog { get; set; }
        public virtual DbSet<OD_Category> OD_Category { get; set; }
        public virtual DbSet<OD_ProductCategoryRelation> OD_ProductCategoryRelation { get; set; }
        public virtual DbSet<OD_Product> OD_Product { get; set; }
    }
}
